config/routes.rb
Testapp::Application.routes.draw do
  root to: 'static_pages#home'

  match '/data',    to: 'static_pages#data'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def data
  	require 'csv'

	start = Array.new(){Array.new()}
	i=1
	while i<13 do
		start.push(CSV.read(Rails.root.join("public/resources/#{i}.csv").to_s))
		i=i+1
	end

	data = Array.new()

	header = Array.new()

	i=0
	while i<start.size do
		header.push(start[i][0][0])
		i=i+1
	end

	j=1
	while j<start[0].size do
		k=1
		while k<start[0][0].size do
			i=0
			while i<start.size do
				if i==0
					data.push(start[i][j][0])
					data.push(start[i][0][k].to_i)
				end
				data.push(start[i][j][k].to_i)
				i=i+1
			end
			if j==1
				data.push("Nepal")
			elsif j==2
				data.push("Afganistan")
			elsif j==3
				data.push("Bangladesh")
			elsif j==4
				data.push("Maldives")
			elsif j==5
				data.push("Pakistan")
			elsif j==6
				data.push("Sri Lanka")
			elsif j==7
				data.push("India")
			elsif j==8
				data.push("Bhutan")
			end
			k=k+1
		end
		j=j+1
	end

	final = data.each_slice(15).to_a

	data_table = GoogleVisualr::DataTable.new

	data_table.new_column('string', 'Location' )
	data_table.new_column('number' , 'Date' )
	i=0
	while i<header.size do
		data_table.new_column('number', header[i] )
		i=i+1
	end
	data_table.new_column('string', 'Location')

	# Add Rows and Values
	data_table.add_rows(final)

	option = { width: 800, height: 440, title: 'Country Performance' }
	@chart = GoogleVisualr::Interactive::MotionChart.new(data_table, option)
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Track Data"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TRACK DATA
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Track Data", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Data Analysis",  data_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <script src='http://www.google.com/jsapi'></script>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  This is a free and open source app. You can use it in any way you like. The datas are from <a href = "http://databank.worldbank.org">World Bank Database.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you have any query related to this application, please forward them to
  <a href="http://www.twitter.com/sushilthe">Sushil Dahal</a> or
  <a href="http://www.twitter.com/sanjanpiya">Sanjan Piya</a>
</p>

app/views/static_pages/data.html.erb
<% provide(:title, 'Data Analysis') %>

<h1>Data Analysis of SAARC Countries</h1>
  <div id='chart'></div>
<%= render_chart @chart, 'chart' %>
<p>The data used here can be found in <a href = "http://databank.worldbank.org">World Bank Database</a> or can be used from <a href = "https://github.com/sushilthe/testapp"> application source</a>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
  <h1>Welcome to Track data App</h1>

  <h2>
  	This app helps in tracking and analysis of various kinds of data.
  </h2>

  <%= link_to "Go to Data Analysis", data_path, class: "btn btn-large btn-primary" %>
</div>